#!/usr/bin/env bash

# Create a webcam stream on port 5001

PORT=5001

echo "Opening Stream on port $PORT"
#gst-launch-1.0 v4l2src device=/dev/video0 ! videoconvert ! video/x-raw,width=1080,framerate=15/1 ! jpegenc ! rtpjpegpay ! udpsink host=10.42.0.1 port=$PORT

gst-launch-1.0 -v v4l2src device=/dev/video0 num-buffers=-1 ! video/x-raw,width=640,height=480, framerate=41/1 ! timeoverlay time-mode="buffer-time" ! jpegenc !  rtpjpegpay !  udpsink host=10.42.0.1 port=5001

